const _Categories = [
    'backpack',
    'school',
    'fashion',
    "men's clothing",
    'shirt',
    'casual',
    'jacket',
    "jewelery",
    "bracelet",
    "women",
    "gold",
    "silver",
    "accessories",
    "rings",
    "earings",
    "electronics",
    "storage",
    "computers",
    "hard drive",
    'usb',
    "portable",
    'ssd',
    'playstation',
    "screens",
    "acer",
    'monitor',
    "gaming",
    "samsung",
    "qled",
    'coats',
    'winter',
    "women's clothing",
    'raincoat',
    'v-neck',
    'cotton'
];

export default _Categories;